spring:
  application:
    name: audit-service
          
info:
  app:
    name: Spring boot audit service Application
    description: ${info.app.name} is Running on ${server.port} port
      
server:
  port: 8090 

paytm.payment:
  sandbox:
    merchantId: ENC(VliTCUZjRRH1JSH0FGicwQPKrXEq4TutqMeZva6e158=)
    merchantKey: ENC(KQJSS3f2xd2DzUhmXea6+bo8WxCndtGOvsQwdhSMaZA=)
    channelId: WEB
    website: DEFAULT
    industryTypeId: Retail
    paytmUrl:  https://securegw.paytm.in/order/process
    callbackUrl: ${webapp.api}pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
  
