INSERT INTO ROLE VALUES (1,1, CURRENT_DATE(),1, CURRENT_DATE(),CURRENT_TIMESTAMP,'ROLE_USER','Active'); 

INSERT INTO ROLE VALUES (2,1, CURRENT_DATE(),1, CURRENT_DATE(),CURRENT_TIMESTAMP,'ROLE_ADMIN','Active'); 

 
